apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: otf5u289h-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/otf5u289h-java-springboot-gitops